# Generated by Django 4.1.5 on 2023-01-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, verbose_name='文章标题')),
                ('content', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('up_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=20)),
                ('screen_1', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_2', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_3', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_4', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_5', models.CharField(blank=True, max_length=50, null=True)),
                ('min_demand', models.CharField(max_length=20)),
                ('min_operator', models.CharField(max_length=20)),
                ('min_cpu', models.CharField(max_length=20)),
                ('min_istorage', models.CharField(max_length=20)),
                ('min_gpu', models.CharField(max_length=20)),
                ('min_directx', models.CharField(db_column='min_directX', max_length=20)),
                ('rec_demand', models.CharField(max_length=20)),
                ('rec_operator', models.CharField(max_length=20)),
                ('rec_cpu', models.CharField(max_length=20)),
                ('rec_istorage', models.CharField(max_length=20)),
                ('rec_gpu', models.CharField(max_length=20)),
                ('rec_directx', models.CharField(db_column='rec_directX', max_length=20)),
                ('min_storage', models.CharField(max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('abstract', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_time', models.PositiveIntegerField()),
                ('producer', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.FileField(default='/avatars/default_avatar.png', upload_to='avatars/')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=20)),
                ('screen_1', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_2', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_3', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_4', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_5', models.CharField(blank=True, max_length=50, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameblog.games')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameblog.articles')),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameblog.comments')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameblog.users')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameblog.levels'),
        ),
        migrations.AddField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameblog.users'),
        ),
        migrations.CreateModel(
            name='ArticleUp',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('article_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameblog.articles')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameblog.users')),
            ],
            options={
                'unique_together': {('article_id', 'user_id')},
            },
        ),
    ]
